### ISSUE TITLE
nothing visible in devices

### ISSUE THREAD

**Issue by steef303** [sydspost/Domoticz-WiZ-connected-plugin#14] opened 2021-11-27 11:31 UTC
nothing visible in devices and log no error messages do you know what I'm doing wrong

![Screenshot_20211127-121802_Samsung Internet](https://user-images.githubusercontent.com/92636131/143679310-58c9798b-bdf5-406f-adfb-e77593a4db6d.jpg)

#

**Comment by sydspost** [comment] 2021-12-02 14:58
The plugin starts with an arp request to determin the ipaddresses of all your devices in your network. And then performs an recursive lookup to determin the hostname of your device. For this step you must have setup /etc/hosts on your domoticz server and added the full qualified domain name and ipaddress of your WIZ connected devices, of setup a DNS server (fi on your router). Also the FQDN-names have to start with the Prefix you've configurated in the plugin, default "WIZ_"

**Comment by sydspost** [comment] 2021-12-13 16:38
Guess this issue is solved and close it. If the issue is niet solved, please deel free to reopen it.

**Closed as completed by sydspost** 2021-12-13 16:38 UTC
