### ISSUE TITLE
Can´t find device

### ISSUE THREAD

**Issue by Klevebrand1** [sydspost/Domoticz-WiZ-connected-plugin#3] opened 2021-10-17 12:26 UTC
Hello.
Script starts fine but do not find any devices.
I can ping the device.
And i can see the device in the DHCP.
![image](https://user-images.githubusercontent.com/92675042/137627115-c65591b0-2245-4c8e-bb47-05d6cec72588.png)

No error in the domoticz log.
![image](https://user-images.githubusercontent.com/92675042/137627023-2ed4e49d-e5db-4686-908b-7be56938a960.png)

**Comment by sydspost** [comment] 2021-10-17 14:43
Can you perform a nslookup of wiz_528a40 ?? Because the plugin first sends a arp request on your subnet and then performs a recursive lookup for each found ip-adres to determe the FQN. The first part of the FQN is matched with the prefix you specified in the settings.

**Comment by Klevebrand1** [comment] 2021-10-17 15:33
Great.
Now i know were too look.

Need to setup a dhcp server for the subnet.
So i can do a recursive lookup.

Or do you have a smarter solution?


Den sön 17 okt. 2021 16:43sydspost ***@***.***> skrev:

**Comment by sydspost** [comment] 2021-12-13 16:30
Guess this issue is solved and close it. If the issue is niet solved, please deel free to reopen it.

**Closed by sydspost** 2021-12-13 16:30 UTC
